- id: minify-json
  name: Minify JSON files
  description: Saves minified copies of JSON and/or JSON5 files.
  entry: minify-json
  language: python
  types_or: [json, json5]

- id: remove-blank-lines
  name: Remove blank lines
  description: Removes blank lines in text-based files.
  entry: remove-blank-lines
  args: ["--force"]
  language: python
  files: "^$"
